templates:
  - src: templates/serversettings.con.tpl
    dest: mods/pr/settings/serversettings.con
  - src: templates/maplist.con.tpl
    dest: mods/pr/settings/maplist.con
  - src: templates/realityconfig_admin.py.tpl
    dest: mods/pr/python/game/realityconfig_admin.py
    reloadable: true
  - src: templates/realityconfig_common.py.tpl
    dest: mods/pr/python/game/realityconfig_common.py
  - src: templates/realityconfig_private.py.tpl
    dest: mods/pr/python/game/realityconfig_private.py
  - src: templates/realityconfig_tracker.py.tpl
    dest: mods/pr/python/game/realityconfig_tracker.py
  - src: templates/reservedslots.con.tpl
    dest: mods/pr/settings/reservedslots.con
    reloadable: true
  - src: templates/rconUsers.dat.tpl
    dest: admin/rconUsers.dat
  - src: templates/__init__.py.tpl
    dest: mods/pr/python/game/__init__.py
  - src: templates/extra/command_debug.py.tpl
    dest: mods/pr/python/game/command_debug.py

defaults:
  - defaults.yaml
